// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:weather_app/models/weather.dart' as _i3;
import 'package:weather_app/services/weather_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWeather_1 extends _i1.SmartFake implements _i3.Weather {
  _FakeWeather_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherService extends _i1.Mock implements _i4.WeatherService {
  MockWeatherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  _i2.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_0(this, Invocation.getter(#httpClient)),
          )
          as _i2.Client);

  @override
  _i6.Future<_i3.Weather> fetchCurrentWeather(String? city) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentWeather, [city]),
            returnValue: _i6.Future<_i3.Weather>.value(
              _FakeWeather_1(
                this,
                Invocation.method(#fetchCurrentWeather, [city]),
              ),
            ),
          )
          as _i6.Future<_i3.Weather>);

  @override
  _i6.Future<_i3.Weather> fetchForecast(String? city) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForecast, [city]),
            returnValue: _i6.Future<_i3.Weather>.value(
              _FakeWeather_1(this, Invocation.method(#fetchForecast, [city])),
            ),
          )
          as _i6.Future<_i3.Weather>);
}
